/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendamysql;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abraham
 */
public class jfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfPrincipal
     */
    DefaultTableModel tablaModelo =new DefaultTableModel();
    List<DatosDTO> listaDatos = new ArrayList<>();
    int vId=0;
    
    public jfPrincipal() {
        initComponents();
        cargartitulos();
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        btnregistra = new javax.swing.JButton();
        btnactualiza = new javax.swing.JButton();
        btnelimina = new javax.swing.JButton();
        btnlimpia = new javax.swing.JButton();
        txtap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Agenda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 44, 334, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Edad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 330, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Correo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 330, -1));

        tablaDatos.setBackground(new java.awt.Color(51, 102, 0));
        tablaDatos.setForeground(new java.awt.Color(255, 255, 255));
        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 533, 204));

        btnregistra.setBackground(new java.awt.Color(255, 255, 255));
        btnregistra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnregistra.setText("Registar");
        btnregistra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnregistra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistraActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 100, -1));

        btnactualiza.setBackground(new java.awt.Color(255, 255, 255));
        btnactualiza.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnactualiza.setText("Actualizar");
        btnactualiza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnactualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizaActionPerformed(evt);
            }
        });
        getContentPane().add(btnactualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 100, -1));

        btnelimina.setBackground(new java.awt.Color(255, 255, 255));
        btnelimina.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnelimina.setText("Eliminar");
        btnelimina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnelimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminaActionPerformed(evt);
            }
        });
        getContentPane().add(btnelimina, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, -1));

        btnlimpia.setBackground(new java.awt.Color(255, 255, 255));
        btnlimpia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnlimpia.setText("Limpiar");
        btnlimpia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, -1));

        txtap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapActionPerformed(evt);
            }
        });
        getContentPane().add(txtap, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, 334, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Apellido Paterno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamActionPerformed(evt);
            }
        });
        getContentPane().add(txtam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 330, -1));

        jLabel6.setText("Apellido Materno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnlimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiaActionPerformed
        // TODO add your handling code here:
        txtnombre.setText("");
        txtap.setText("");
        txtam.setText("");
        txtedad.setText("");
        txtcorreo.setText("");
    }//GEN-LAST:event_btnlimpiaActionPerformed

    private void btnregistraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistraActionPerformed
        // TODO add your handling code here:
        DatosDTO datos = new DatosDTO();
        ConexionDAO conexion = new ConexionDAO();
        
        datos.setNombre(txtnombre.getText());
        datos.setAp(txtap.getText());
        datos.setAm(txtam.getText());
        datos.setEdad(txtedad.getText());
        datos.setCorreo(txtcorreo.getText());
        
        if (conexion.inserta(datos)){
            JOptionPane.showMessageDialog(this, "Se registro correctamente...","Registro",JOptionPane.INFORMATION_MESSAGE);
            tablaModelo = (DefaultTableModel) tablaDatos.getModel();
            tablaModelo.getDataVector().removeAllElements();
        }else{
            JOptionPane.showMessageDialog(this, "Error al insertar...","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnregistraActionPerformed

    private void tablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseClicked
        // TODO add your handling code here:
        int nfilas = 0;
        int filas = 0;
        nfilas = tablaDatos.getSelectedRowCount();
        if (nfilas == 1){
        filas = tablaDatos.getSelectedRow();
        vId = (int) tablaDatos.getValueAt(filas, 0);
        txtnombre.setText((String)tablaDatos.getValueAt(filas, 1) );
        txtap.setText((String)tablaDatos.getValueAt(filas, 2) );
        txtam.setText((String)tablaDatos.getValueAt(filas, 3) );
        txtedad.setText((String)tablaDatos.getValueAt(filas, 4) );
        txtcorreo.setText((String)tablaDatos.getValueAt(filas, 5) );
    }
    }//GEN-LAST:event_tablaDatosMouseClicked

    private void btnactualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizaActionPerformed
        // TODO add your handling code here:
        ConexionDAO conexion = new ConexionDAO();
        DatosDTO datos = new DatosDTO ();
        
        datos.setId(vId);
        datos.setNombre(txtnombre.getText());
        datos.setAp(txtap.getText());
        datos.setAm(txtam.getText());
        datos.setEdad(txtedad.getText());
        datos.setCorreo(txtcorreo.getText());
        
        if(conexion.actualiza(datos)){
            JOptionPane.showMessageDialog(this, "se registro correctamente...","Registro", JOptionPane.INFORMATION_MESSAGE);
            tablaModelo = (DefaultTableModel)tablaDatos.getModel();
            tablaModelo.getDataVector().removeAllElements();
            cargar();
            
        }else{
            JOptionPane.showMessageDialog(this, "Error al insertar","Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnactualizaActionPerformed

    private void btneliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminaActionPerformed
        // TODO add your handling code here:
        DatosDTO datos = new DatosDTO();
        ConexionDAO conexion = new ConexionDAO();
        
        datos.setId(vId);
        
        if(conexion.eliminar(datos)){
            JOptionPane.showMessageDialog(this, "se elimino correctamente...","Registro", JOptionPane.INFORMATION_MESSAGE);
            tablaModelo = (DefaultTableModel)tablaDatos.getModel();
            tablaModelo.getDataVector().removeAllElements();
            cargar();
        }else{
            JOptionPane.showMessageDialog(this, "Error al elimnar","Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btneliminaActionPerformed

    private void txtapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapActionPerformed

    private void txtamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamActionPerformed
    
    private void cargar() {
     ConexionDAO conexion = new ConexionDAO();
     if (conexion.cargar()){
         listaDatos = conexion.getDatos();
     }else{
         JOptionPane.showMessageDialog(this, "Error al cargar", "Error",JOptionPane.INFORMATION_MESSAGE);
         }
     if (listaDatos.size() > 0 && listaDatos !=null){
         cargarcontenido();
     }
    }
    
    private void cargarcontenido() {
        Object[] filatabla = new Object[6];
        for (DatosDTO datos : listaDatos){
            filatabla[0]=datos.getId();
            filatabla[1]=datos.getNombre();
            filatabla[2]=datos.getAp();
            filatabla[3]=datos.getAm();
            filatabla[4]=datos.getEdad();
            filatabla[5]=datos.getCorreo();
            tablaModelo.addRow(filatabla);
        }
        tablaDatos.setModel(tablaModelo);
    }
    
    
    private void cargartitulos() {
        tablaModelo.addColumn("Id");
        tablaModelo.addColumn("Nombre");
        tablaModelo.addColumn("Apellido P");
        tablaModelo.addColumn("Apellido M");
        tablaModelo.addColumn("Edad");
        tablaModelo.addColumn("Correo");
        tablaDatos.setModel(tablaModelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiza;
    private javax.swing.JButton btnelimina;
    private javax.swing.JButton btnlimpia;
    private javax.swing.JButton btnregistra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField txtam;
    private javax.swing.JTextField txtap;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
